### ISSUE TITLE
Function iter_merge_sort has bug where array with length 2 is not sorted

### ISSUE THREAD

**Issue by dangbb** [TheAlgorithms/Python#6152]
[Test Report - Iter merge sort function.pdf](https://github.com/TheAlgorithms/Python/files/8698882/Test.Report.-.Iter.merge.sort.function.pdf)
Here all the report.

**Comment by dangbb** [comment]
Also, it has a bug where user can't enter empty input.
The following is the log:
`Traceback (most recent call last):
  File "sorts\iterative_merge_sort.py", line 73, in <module>
    unsorted = [int(item.strip()) for item in user_input.split(",")]
  File "sorts\iterative_merge_sort.py", line 73, in <listcomp>
    unsorted = [int(item.strip()) for item in user_input.split(",")]
ValueError: invalid literal for int() with base 10: ''`
