### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by Miltonbhowmick** [TheAlgorithms/Python#9040]
### What would you like to share?

I can not understand about the build error of this PR https://github.com/TheAlgorithms/Python/pull/9039
If anyone can help me out of this, i will be glad.

Thanks in advance.

**Comment by tianyizheng02** [comment]
The build log makes it very clear what the issue is:
```
=================================== FAILURES ===================================
___________________ [doctest] graphs.uniform_search_cost.ucs ___________________
030 
031     Returns a list of integer values which are result of optimal distance
032     >>> graph_data = [[1, 2], [2, 3], [4], [4, 5], [6], [6], [], []]
033     >>> distance = {(0, 1): 2, (0, 2): 1, (1, 2): 5, (1, 3): 10, (2, 4): 3, (3, 4): 2,
UNEXPECTED EXCEPTION: SyntaxError("'{' was never closed", ('<doctest graphs.uniform_search_cost.ucs[1]>', 1, 12, 'distance = {(0, 1): 2, (0, 2): 1, (1, 2): 5, (1, 3): 10, (2, 4): 3, (3, 4): 2,\n', 1, 0))
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/doctest.py", line 1351, in __run
    exec(compile(example.source, filename, "single",
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<doctest graphs.uniform_search_cost.ucs[1]>", line 1
    distance = {(0, 1): 2, (0, 2): 1, (1, 2): 5, (1, 3): 10, (2, 4): 3, (3, 4): 2,
               ^
SyntaxError: '{' was never closed
/home/runner/work/Python/Python/graphs/uniform_search_cost.py:33: UnexpectedException
```
Please read the build logs to debug your PR's issues, and please keep discussions about your PRs within the PRs themselves.

**Comment by Miltonbhowmick** [comment]
I have done with new PR. Thanks for your time and hoping for my first contribution. :)
